blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Docs
    url: https://webcrate.deta.dev/docs
    about: Checkout WebCrate's documentation before opening an issue.
  - name: ğŸš€ Feature Request
    url: https://github.com/WebCrateApp/feedback/discussions/new?category=ideas
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/WebCrateApp/feedback/discussions/new?category=q-a
    about: Ask the community for help
  - name: ğŸ“§ Contact support
    url: https://webcrate.deta.dev/contact
    about: Contact WebCrate's support privately